config/routes.rb
Rails.application.routes.draw do


  root 'chatroom#index'
  get 'login', to: 'sessions#new'
  get 'signup', to: 'users#new'
  resources :users
  post 'login', to: 'sessions#create'
  post 'signup', to: 'users#create'
  delete 'user', to: 'users#destroy'
  delete 'logout', to: 'sessions#destroy'
  post 'message', to: 'messages#create'



end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord

  belongs_to :user
  validates :body, presence: true
  scope :custom_display, -> { order(:created_at).last(20) }
end

app/models/user.rb
class User < ApplicationRecord

  validates :username, presence: true, uniqueness: { case_sensitive: false }, length: {minimum: 3, maximum: 25 }
  has_secure_password
  has_many :messages, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  helper_method :current_user, :logged_in? # to use in all views

    def current_user
      @current_user || User.find(session[:user_id]) if session[:user_id]
    end

    def logged_in?
      !!current_user
    end

    def require_user
      if !logged_in?
        flash[:alert] = "You must be logged in to perform that action"
        redirect_to login_path
      end
    end


end

app/controllers/chatroom_controller.rb
class ChatroomController < ApplicationController

 before_action :require_user

  def index
    @message = Message.new
    @messages = Message.custom_display
    @users = User.all

  end


end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

before_action :require_user

  def create
    message = current_user.messages.build(message_params)

    if message.save
      redirect_to root_path
    end

  end

  private

  def message_params
    params.require(:message).permit(:body)
  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

 before_action :logged_in_redirect, only: [:new, :create]

  def new
  end

  def create
    user = User.find_by(username: params[:session][:username].downcase)
    if user && user.authenticate(params[:session][:password])
      session[:user_id] = user.id
      flash[:success] = "Logged in successfully"
      redirect_to root_path
    else
      flash.now[:error] = "There was something wrong with your login details"
      render 'new'
    end
  end

  def destroy

    session[:user_id] = nil
    flash[:success] = "Logged out successfully"
    redirect_to signup_path

  end

  private

  def logged_in_redirect

    if logged_in?
      flash[:error] = "You are already logged in"
      redirect_to root_path
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :set_user, only:[:show, :edit, :update, :destroy]
  before_action :require_user, only:[:edit, :index, :update]
  # before_action :require_same_user, only:[:edit, :update, :destroy]

    def show


    end

    def index

    end

    def new
      @user = User.new
    end

    def edit

    end

   def create
     @user = User.new(params_user)
     if @user.save
       session[:user_id] = @user.id
       flash[:notice] = "Welcome to the Message me, you have successfully Sign Up"
       redirect_to root_path
     else
       flash[:error] = "There was something wrong with your details"
       redirect_to signup_path
   end
  end

    def update

      if @user.update(params_user)
        flash[:notice] = "Your account information was updated successfully"
        redirect_to root_path
      else
        render 'edit'
      end
    end

     def destroy

         @user.destroy
         session[:user_id] = nil
         flash[:notice] = "Account and all associated messages successfully deleted"
         redirect_to signup_path

     end



  private

    def params_user
      params.require(:user).permit(:username,:password)
    end

    def set_user
    @user = User.find(params[:id])
    end

    # def require_same_user
    #   if current_user != @user && !current_user.admin?
    #     flash[:alert] = "You can only edit or delete your own account"
    #   end
    # end

  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/chatroom_helper.rb
module ChatroomHelper
end

app/views/chatroom/index.html.erb
<h4 class="ui center aligned medium icon header">
  <i class="circular blue user secret icon"></i>
  Say something
</h4>

<div class="ui two column grid">
    <div class="twelve wide column">
      <div class="ui fluid raised card chatbox">
            <div class="content" id="messages">
                <div class="ui feed" id="message-container">
                 <%= render @messages %>
                </div>
            </div>


       <div class="extra content">
         <%= form_for(@message, html: {class:"ui reply form", role: "form"}, url: message_path, method: "POST", remote: true ) do |f|%>
           <div class="field">
             <div class="ui fluid icon input">
               <%= f.text_field :body %>
               <%= f.button '<i class="bordered inverted blue edit icon"></i>'.html_safe %>
             </div>
           </div>
         <% end %>
       </div>
      </div>
    </div>



  <div class="four wide column">
    <div class="ui fluid raised card chatbox">
        <div class="content">
        <div class="ui fluid raised inverted vertical menu">
              <a class="active item">
                Home
              </a>
              <a class="item">
                Messages
              </a>
              <a class="item">
                All Users
              </a>
              <div class="divider"></div>
                <%= render 'users/users' %>
                <div class="divider"></div>

              </div>
        </div>
    </div>
  </div>
</div>

app/views/layouts/_footer.html.erb
<div class="ui inverted vertical footer segment">
  <div class="ui container center aligned">
    Ruby -v 2.6.10   /   Rails -v 5.2.8.1   /   Semantic-UI Front End
    &nbsp&nbsp&nbsp<a href="https://www.linkedin.com/in/fabian-martinez-02589a80/"><i class="linkedin square icon big"></i></a>
  </div>
</div>

app/views/layouts/_messages.html.erb
<% flash.each do | message_type, message_content | %>
  <div class="ui <%= message_type %> message transition">
    <i class="close icon"></i>
    <div class="header">
     <%= message_content %>
    </div>
  </div>
<% end %>

app/views/layouts/_navigation.html.erb
<%= link_to "Chatroom", root_path, class:"item" %>
<a class="item">Messages</a>
  <div class="right menu">
    <% if logged_in? %>
       <div class="ui simple dropdown link item">

         <span class="text"> Profile [ <%= current_user.username %> ]  </span>
              <i class="dropdown icon"></i>
              <div class="menu">

                    <%= link_to "Edit", edit_user_path(current_user), class:"item" %>
                    <%= link_to "Logout", logout_path, method: :delete, class:"item" %>

                  <!-- <div class="divider"></div> --><% end %>
              </div>
      </div>


  </div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MessageMe</title>
<meta name="viewport" content="width=device-width, initial-scale=1">
    <%= favicon_link_tag %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>
    <div class="ui inverted menu">
      <div class="ui container">
          <%= render 'layouts/navigation' %>
       </div>
    </div>
  <body>
    <div class="ui container">
      <%= render 'layouts/messages' %>
      <%= yield %>
      <%= render 'layouts/footer' %>
    </div>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="event">
  <div class="content">
    <div class="summary">
       
        <em><%= message.user.username %></em> :
        <%= message.body %>

    </div>
  </div>
</div>

app/views/shared/_errors.html.erb
<% if obj.errors.any? %>
  <div class="ui message transition">
    <h3 class="ui center aligned container">The following errors prevented the <%= obj.class.name.downcase %> from being saved</h3>

    <i class="close icon"></i>


    <% obj.errors.full_messages.each do |msg| %>
          <ul>
           <%= msg %>
          </ul>
    <% end %>

    </div>

<% end %>

app/views/users/_form.html.erb

<%= form_with(model: @user,html:{ class: "ui form", role: "form" }, local:true, data: { turbo: false }) do |f| %>
<div class="field">
  <%= f.label :username, "Username" %>
    <div class="ui left icon input">
      <%= f.text_field :username, placeholder: "Create Username" %>
      <i class="user icon"></i>
    </div>
  </div>
  <div class="field">
    <%= f.label :password, "Password" %>
    <div class="ui left icon input">
      <%= f.password_field :password, placeholder: "Choose a Password" %>
      <i class="lock icon"></i>
    </div>
  </div>
  <%= f.submit(@user.new_record? ? "Sign up" : "Update account", class:"ui blue submit button") %>
  <% end %>

app/views/users/_users.html.erb

<% @users.each do | user | %>
<a class="active item">

     <%= user.username %>
   
   </a>
<% end %>

app/views/users/edit.html.erb
<h3 class="ui center aligned container">Edit Your - <em> Profile </em> </h3>
<h4 class="ui center aligned medium icon header">
  <i class="circular blue steam symbol icon"></i>
  Edit your settings

</h4>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed unstackable grid">
    <div class="column">
      <%= render 'form' %>
    </div>
    <div class="middle aligned column">

              <%= link_to 'Delete Account', user_path, class: "ui red submit button", method: :delete, onclick: "return confirm('Are you sure?')"  %>

    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>

app/views/users/new.html.erb
<h3 class="ui center aligned container">Welcome to message me - <em> a complete Chat App </em> </h3>
<h4 class="ui center aligned medium icon header">
  <i class="circular blue themeisle icon"></i>
  Create new user to continue

</h4>

<div class="ui placeholder segment">
  <div class="ui two column very relaxed unstackable grid">
    <div class="ui middle aligned column">
      <%= link_to 'Login', login_path, class: "ui blue submit button" %>
    </div>
    <div class="middle aligned column">
      <div class="column">
        <%= render 'form' %>
      </div>

    </div>
  </div>
  <div class="ui vertical divider">
    Or
  </div>
</div>